flags: {}
packages:
- '.'
- location:
    git: https://github.com/AccelerateHS/accelerate.git
    commit: 08d63ed03a8224000906f11d05afeafb3c6d977e
  extra-dep: true
- location:
    git:   https://github.com/AccelerateHS/accelerate-io.git
    commit: f4c84a5c961345bf65059f555f21c6e8bf3070a1
  extra-dep: true
extra-deps:
- 'unique-0'
resolver: lts-7.17
